version: "3"

services:
  restful-api:
    build: .
    container_name: "${APP_NAME}-api"
    environment:
      MONGO_URI: "${MONGO_URI}"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "${APP_NAME}-mongodb"
    ports:
      - "27017:27017"

  mongo-gui:
    container_name: "${APP_NAME}-mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
      MONGO_URL: "${MONGO_URI}"
    depends_on:
      - mongodb
